services:
  syslog-sender:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - otel-collector
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: syslog-sender
      # OTEL_METRICS_EXPORTER: none # disable export metrics
      # OTEL_TRACES_EXPORTER: none  # disable trace export
    networks:
      - otel-network


  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/docker/collector/otel-collector-config.yaml"]
    volumes:
      - ./docker/collector/otel-collector-config.yaml:/etc/docker/collector/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "514:514" # Syslog TCP
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge

